### ISSUE TITLE
Dernières mises à jour absentes de mes fichiers mergés !...

### ISSUE THREAD

**Issue by ColinB33** [Chartes-TNAH/corneille#103]
! WARNING !

@LucenceIng @MyleneM @MaylisRibette @Paulinelvq concernant mes fichiers qui ont été mergés (crnl003 / 014 / 020 / 021 / 022 et 026) je n'ai pas pu faire les dernières mises à jour en rapport avec notre modèle crnl023 (notamment l'ajout xml + modif. xml:lang)

**Comment by MyleneM** [comment]
@ColinB33 Tu n'as pas pu parce que ça ne marchait pas ou parce que tu le feras demain ?

**Comment by Paulinelvq** [comment]
J'allais te poser la même question
