### ISSUE TITLE
027 doublon, 027 et 019 fautifs

### ISSUE THREAD

**Issue by MaylisRibette** [Chartes-TNAH/corneille#109]
Comment supprimer un dossier parasite issu d'une coquille ? Et qu'est-ce qui cloche dans le vrai 027 et dans 019 ?

**Comment by MaylisRibette** [comment]
xmlns:rdf est bien dans ti:work

**Comment by MyleneM** [comment]
@MaylisRibette Merci pour ton aide (et celle de @LucenceIng) Je viens de corriger!

**Comment by LucenceIng** [comment]
Ok pour la coquille du dossier #111
