### ISSUE TITLE
Je ne comprends rien

### ISSUE THREAD

**Issue by Paulinelvq** [Chartes-TNAH/corneille#113]
Concrètement, mes fichiers passent ou passent pas (je ne sais même pas où on peut voir ça) ? Qu'est-ce que je dois faire pour qu'ils passent ? J'ai fait toutes les modifications décidées lors de nos différentes réunions. 

Je n'ai jamais fait de xml, je ne comprends strictement rien à ce que je fais, en toute honnêteté.

**Comment by Paulinelvq** [comment]
Mais je ne vois même pas lesquels sont passés ou pas !

**Comment by Paulinelvq** [comment]
Et j'ai tout envoyé d'un ordi de l'école hier parce que je n'y arrivais pas du mien. Pourquoi ? C'est un mystère à nouveau...

**Comment by LucenceIng** [comment]
D'après la dernière pull request, le fichier cts.xml de crnl011 n'est pas bon. 
Les autres passent.

C'est le fichier cts.xml qui pose problème.

 Il manque l'espace de nom rdf, à mettre dans la balise ti:work (xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"). 

Les ti:edition sont bizarres : l'un parle de la conquête de la Toison d'or, l'autre de Martial's Epigrammata (oubli de modification d'un copié-collé ?), alors qu'il s'agit du texte de Cinna.

Le fichier en question réfère à 3 fichier tei, du coup, il me semble qu'il doit y avoir trois ti:edition et non deux, Pour chaque ti:edition, il y a un workUrn, et ça, c'est bon, mais il doit y avoir qu'un seul lieu urn (je pense que c'est ça qui cause l'erreur principale) qui réfère à l'édition en question (premier ti:edition correspond donc à la balise :
<ti:edition 
      workUrn="urn:cts:freLit:crnl026799472.crnl011"  
urn="urn:cts:freLit:crnl026799472.crnl011.obvilchartes11-1">, le deuxième : <ti:edition 
      workUrn="urn:cts:freLit:crnl026799472.crnl011"  
urn="urn:cts:freLit:crnl026799472.crnl011.obvilchartes11-2"> ).

Les dates : <dc:created>1682</dc:created> et <dc:dateSubmitted>2014</dc:dateSubmitted> doivent avoir un attribut rdf:datatype --> <dc:created rdf:datatype="xsd:gYear">1682</dc:created>

Les ti:label doivent avoir un attribut xml:lang="fr" et non "mul" --> pas <ti:label xml:lang="mul"> mais <ti:label xml:lang="fr">.

Par contre, l'identifiant même ne correspond pas. Il doit s'agir du urn:cts:freLit:crnl026799472.crnl011, ce qui n'est pas le cas partout.

Je ne sais pas si c'est clair ?

**Comment by Paulinelvq** [comment]
Merci beaucoup pour ces explications !!!
