### ISSUE TITLE
Euh, et si on faisait coïncider les dates du fichier cts avec celles du fichier tei ?

### ISSUE THREAD

**Issue by MaylisRibette** [Chartes-TNAH/corneille#117]
Tout est dans le titre…

**Comment by LucenceIng** [comment]
Je crois que c'est le cas nan ? On s'est basé sur ça normalement... Sauf peut-être petites erreurs ?

**Comment by MaylisRibette** [comment]
En fait, parfois, c'est une période exprimée par deux dates (1631-1640 ou qch comme ça), ce qui n'est peut-être pas très propre dans un fichier de métadonnées. Quand c'est une seule date et que les dates d'écriture, de création et de publication diffèrent, la date indiquée par Paul Fièvre dans mes fichiers est la date de création indiquée par Wikipédia, plus un an ; je ne sais pas à quoi cela correspond, et sachant que pour "Mélite", il y a quatre ans entre l'écriture et la création, j'ai mis celle de l'écriture… On peut encore changer.

**Comment by MaylisRibette** [comment]
Bon, on laisse comme ça.
