### ISSUE TITLE
Problème travis sur les documents XML de texte

### ISSUE THREAD

**Issue by LucenceIng** [Chartes-TNAH/corneille#126]
Comment réussir à faire valider nos documents XML de texte ? 

Le schéma de validation n'est pas bon, mais ça, c'est pas de notre ressort. 

Certains textes n'ont pas le bon urn.
Il faut ajouter un @xml:lang="fr" dans la balise <text>.

Plus gros problème, Travis renvoie toute une suite d'erreurs qui semble liées au fait qu'il ne peut pas parser le document. Le texte 23 passe (il faut juste modifier l'xml:lang), mais il a un structure différente des autres. 

QUOI FAIRE ?
Il faut faire des tests jusqu'à ce qu'on arrive à valider ? 
#124 #125 

@ColinB33 @Paulinelvq @MaylisRibette @MyleneM

**Comment by LucenceIng** [comment]
Alors, ça fonctionne : cf #127 
Il faut donc remplacer dans le cRefPattern le chemin XPath. A part le 23, ils semblent tous être construits avec <div1> et <div2>.
Il faut donc mettre : "#xpath(/tei:TEI/tei:text/tei:body/tei:div1/tei:div2//tei:l[@n='$1'])" dans l'attribut @replacementPattern.

Du coup, après ces 3 changement (urn pour ceux qui en ont besoin, xml:lang, et le cRefPattern, il n'y aura plus qu'un seul message d'erreur lié à la validation de la DTD, dont on ne s'occupe pas).

**Comment by MaylisRibette** [comment]
Merci Lucence !!!

**Comment by ColinB33** [comment]
Super ! merci @LucenceIng

**Comment by MyleneM** [comment]
@LucenceIng Merci!
