### ISSUE TITLE
Répartition du travail

### ISSUE THREAD

**Issue by LucenceIng** [Chartes-TNAH/corneille#2]
31 textes différents donc 6 textes chacun.e et deux ensemble. 

@MyleneM
Cid (2)
Agésilas
Andromède
Attila
Clitandre
Don Sanche

@MaylisRibette 
Médée (2)
Galerie du Palais
Heraclius
Horace
Illusion comique
Mélite

@ColinB33 
Veuve (2)
Mort Pompée
Nicomède
Oedipe
Othon
Pertharite

@Paulinelvq
Cinna (3)
Place royale
Polyeucte
Pulchérie
Rodogune
Certorius

@LucenceIng
Menteur (Suite Menteur)
Sophonisbe
Suivante
Surena
Théodore
Tite

Est-ce que ça va à tout le monde ?

On le fait ensemble : Toison.

**Comment by MaylisRibette** [comment]
Oui, ça me va.

**Comment by MyleneM** [comment]
Oui, parfait ! Merci Lucence:)

**Comment by MaylisRibette** [comment]
Mais comment devons-nous identifier les différentes éditions d'un même texte ?

**Comment by Paulinelvq** [comment]
Parfait ! Merci beaucoup Lucence !
Encore désolée d'avoir dû partir plus tôt.

**Comment by ColinB33** [comment]
C'est bon pour moi ! :)

**Comment by MaylisRibette** [comment]
Vu qu'on s'est accordés pour traiter ensemble les différentes versions d'une même pièce ainsi que "Le Menteur" et "La Suite du Menteur" et pour classer les pièces par ordre chronologique dans des dossiers numérotés de 001 à 031 (correspondant chacun à un espace "work" de l'urn:cts), voici une liste des pièces suivies de leur date et de leur numéro de dossier, étant donnée que chaque pièce est datée d'après sa première édition et "La Suite du Menteur" à la date du "Menteur" (source : Wikipédia) :

    Mélite (1629, première œuvre, comédie) 001
    Clitandre ou l’Innocence persécutée (1631) 002
    La Veuve (1632) 003
    La Galerie du Palais (1633) 004
    La Suivante (1634) 005
    La Place royale (1634) 006
    Médée (1635) 007
    L’Illusion comique (1636) 008
    Le Cid (1637) 009
    Horace (1640) 010
    Cinna ou la Clémence d'Auguste (1641) 011
    Polyeucte (1642) 012
    Le Menteur (1644) 013
    La Mort de Pompée (1643) 014
    Rodogune (1644) 015
    Théodore (1646) 016
    Héraclius (1647) 017
    Don Sanche d’Aragon (1649) 018
    Andromède (1650) 019
    Nicomède (1651) 020
    Pertharite (1651) 021
    Œdipe (1659) 022
    La Toison d'or (1660) 023
    Sertorius (1662) 024
    Sophonisbe (1663) 025
    Othon (1664) 026
    Agésilas (1666) 027
    Attila (1667) 028
    Tite et Bérénice (1670) 029
    Pulchérie (1672) 030
    Suréna (1674) 031

**Comment by MaylisRibette** [comment]
@MyleneM
Cid (2) 009
Agésilas 027
Andromède 019
Attila 028
Clitandre 002
Don Sanche 018

**Comment by LucenceIng** [comment]
@ColinB33
Veuve (2) 003
Mort Pompée 014
Nicomède 020
Oedipe 022
Othon 026
Pertharite 021

**Comment by ColinB33** [comment]
@LucenceIng 
Menteur (Suite Menteur) : 013
Sophonisbe : 025
Suivante : 005
Surena : 031
Théodore : 016
Tite : 029

**Comment by MaylisRibette** [comment]
et moi :)

@MaylisRibette
Médée (2) 007
Galerie du Palais 004
Heraclius 017
Horace 010
Illusion comique 008
Mélite 001

**Comment by ColinB33** [comment]
@Paulinelvq
Cinna (3) : 011
Place royale : 006
Polyeucte : 012
Pulchérie : 030
Rodogune : 015
Certorius : 024

**Comment by MaylisRibette** [comment]
et 023 pour tout le monde
