### ISSUE TITLE
Problème pour pusher un dossier

### ISSUE THREAD

**Issue by MyleneM** [Chartes-TNAH/corneille#3]
J'ai un problème pour pusher un dossier.
Lucence et moi avons créé un dossier 'data' dans lequel se trouvent les dossiers de pièces (vides). Cela correspond à la structure et devrait ainsi nous permettre de pouvoir travailler sur les textes. Cependant, nous rencontrons des difficultés pour le pusher sur Github.
On a créé une branche de structure qui nous a permis de pusher le fichier 'travis', mais nous ne parvenons pas à vous transmettre le dossier 'data'. Le terminal nous indique pourtant que les branches sont à jour... !

D'où pourrait venir le problème @PonteIneptique  ?

**Comment by PonteIneptique** [comment]
Il est impossible de pusher un dossier vide sous git. Seuls les dossiers comprenant des fichiers (ou des dossiers comprenant eux-même des fichiers) peuvent être pushés.
