### ISSUE TITLE
Problème avec Travis pour les pull request

### ISSUE THREAD

**Issue by ColinB33** [Chartes-TNAH/corneille#35]
@PonteIneptique on a un problème avec le document travis.yml
Comme vous nous l'avez indiqué, nous avons modifié le fichier travis.yml en remplaçant "epidoc" par "tei" mais cette modification ne semble pas avoir été prise en compte lorsque les tests Travis sont effectués dans les "pull request"

D'où peut venir l'erreur ?

**Comment by MaylisRibette** [comment]
C'est pas pour dénoncer mes petits camarades, mais les "theses" ont aussi une croix rouge là-dessus, et les "geste" int ajouté une commande --alowfailure…

**Comment by PonteIneptique** [comment]
Il faut cliquer sur la petite croix rouge et voire si vos modifications ont eu de l'effet : https://travis-ci.org/Chartes-TNAH/corneille/builds/354409613?utm_source=github_status&utm_medium=notification
