### ISSUE TITLE
Petite modification à effectuer pour les modifications à faire dans <refsDecl>

### ISSUE THREAD

**Issue by ColinB33** [Chartes-TNAH/corneille#36]
Concernant les modifications à effectuer dans la balise <refsDecl> du fichier texte (pièce de théâtre) une petite erreur s'est glissée dans ce qu'on a fait tout à l'heure qu'il faut modifier : 

Avec l'erreur (les doubles guillemets de @n="1") : 

<cRefPattern 
      n="level1"
      matchPattern="(\w+)"
      replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div//tei:l[@n="1"])">

Avec erreur corrigée (les doubles guillemets remplacés par de simples guillements @n="1" => @n='1') : 

<cRefPattern 
      n="level1"
      matchPattern="(\w+)"
      replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div//tei:l[@n='1'])">

**Comment by Paulinelvq** [comment]
Tu m'avais dit de faire ainsi : 
<cRefPattern 
          n="level1"
          matchPattern="(\w+)"
          replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div//tei:l[@n='$1'])">
Ce n'est pas bon avec le $ ? Je n'y connais rien en TEI ! 👎

**Comment by LucenceIng** [comment]
Du coup, il faut faire comme dans #126 (sauf exception type crnl023)
