### ISSUE TITLE
Date dans le fichier cts ?

### ISSUE THREAD

**Issue by MaylisRibette** [Chartes-TNAH/corneille#6]
Comme l'a remarqué Lucence, les dates originelles d'édition ne figurent pas dans les exemples de fichiers __cts__.xml fournis dans les guidelines, ni, partant, dans les nôtres. De plus, comme le rappelle Pauline, la date de création d'une pièce et sa date d'édition ne coïncident pas forcément, et, ajouté-je, il peut y avoir plusieurs éditions d'une même pièce dans un même dossier. Voici une discussion sur le sujet : https://github.com/OpenGreekAndLatin/First1KGreek/issues/1014 ; la recommandation finale d'@AlisonBabeu est de se servir de ceci : http://www.loc.gov/standards/mods/mods-dcsimple.html

**Comment by MaylisRibette** [comment]
On peut ajouter parmi les éléments <dc:xxx/> dans <cpt:structured-metadata/> un élément <dct:dateOther/> avec des attributs creation, edition1 et edition2 :
<dct:dateOther xml:lang="fr" type="creation"></dct:dateOther> pour la création d'une pièce, et passim.

**Comment by LucenceIng** [comment]
Et en même temps, ajouter un <dc:publisher> pour chaque édition : <dc:publisher xml:lang="fr">blabla</dc:publisher>, en-dessous de la date.

**Comment by MaylisRibette** [comment]
Une petite commande pour ajouter les balises de dates (dans le terminal, dans le dossier corneille) :
sed -ir "/<\/dct:dateCopyrighted>/ a\ \n<dct:dateOther xml:lang=\"fr\" type=\"creation\"><\/dct:dateOther>\n<dct:dateOther xml:lang=\"fr\" type=\"edition1\"><\/dct:dateOther>\n<dct:dateOther xml:lang=\"fr\" type=\"edition2\"><\/dct:dateOther>" data/crnl026799472/*/__cts__.xml
étant entendu que les dates elles-mêmes doivent être ajoutées manuellement.
sed est un éditeur en ligne de commande ; les options i et r permettent respectivement d'éditer directement le fichier courant et de se servir d'expressions régulières, dans lesquelles il faut échapper un certain nombre de caractères, en particulier / qui sert à encadrer le motif recherché.
Je n'ai pas ajouté la balise dc:publisher parce qu'elle existe déjà, avec le contenu "Théâtre Classique". Peut-être avec un attribut ?
La même chose pour l'espace de nom manquant :
sed -ir "/xmlns:dct=\"http:\/\/purl.org\/dc\/terms\/\"/ a\ \nxmlns:dct=\"http:\/\/www.w3.org\/1999\/02\/22-rdf-syntax-ns#\"" data/crnl026799472/*/__cts__.xml
− ça fait beaucoup d'échappements, on se croirait rue Saint-Jacques ! Je me suis dit que ça ne valait pas la peine de faire une feuille de style, puisque ça revenait à insérer manuellement l'adresse de la feuille de style dans chaque fichier en plus du reste…
Une petite dernière pour avoir une belle indentation :

**Comment by MaylisRibette** [comment]
Il y avait ça, aussi :
https://github.com/Chartes-TNAH/theses/wiki/5.-Transformer-XML-en-masse-via-OxyGen

**Comment by MaylisRibette** [comment]
L'erreur était mienne, une étourderie qui m'apprendra à travailler de nuit !
`sed -ir "s/xmlns:dct=\"http:\/\/www.w3.org\/1999\/02\/22-rdf-syntax-ns#\"/xmlns:rdf=\"http:\/\/www.w3.org\/1999\/02\/22-rdf-syntax-ns#\"/g" data/crnl026799472/*/__cts__.xml
`
pour la corriger ; autrement, on peut remplacer directement `dct` par `rdf` dans l'espace de nom ajouté par la précédente commande.

**Comment by ColinB33** [comment]
@MaylisRibette  et @LucenceIng  concernant les balises à rajouter pour les dates d'édition dans le fichier cts.xml qu'avez vous choisi comme solution ?
Utilisation de la balise <dc:publisher> ? Ou bien de la balise <dct:dateOther xml:lang="fr" type="edition1"> ?

**Comment by LucenceIng** [comment]
Les deux il me semble... Dans mon esprit, c'était : <dct:dateOther> pour la date et <dc:publisher> pour le nom de l'éditeur concerné par la date . (?)

**Comment by MaylisRibette** [comment]
Donc avec les mêmes attributs pour le diffuseur que pour la date ?

**Comment by LucenceIng** [comment]
Problème réglé : dc:created et dc:dateSubmitted; cf fichiers à jour sur le code
