### ISSUE TITLE
Merge des pull request

### ISSUE THREAD

**Issue by LucenceIng** [Chartes-TNAH/corneille#72]
On va merger les pull request actuelles pour avoir une branche master propre, qu'on pourra puller. Et ensuite il faudra retravailler les fichiers et refaire les pull requests.

**Comment by MyleneM** [comment]
@ColinB33 @Paulinelvq il faudrait que vous modifiiez vos fichiers. Le modèle à suivre est le crnl023 #61 et #62

**Comment by MaylisRibette** [comment]
Bon, on poupoule et on fait les déclarations xml, et ça règle tous nos problèmes, c'est ça ?

**Comment by Paulinelvq** [comment]
@LucenceIng Euh, je vais avoir un soucis, je ne peux pas pusher de mon ordi

**Comment by Paulinelvq** [comment]
Mais c'est que le fichier où il y a plusieurs versions qui pose pb ou les autres aussi ? Je dois avouer que je suis un peu larguée là !

**Comment by MyleneM** [comment]
@Paulinelvq De quel fichier parles-tu exactement ?

**Comment by Paulinelvq** [comment]
Cinna (3) : 011

J'ai suivi ce qu'on avait fait pour le 023, et je n'ai pas vu de différence entre mes fichiers cts et les vôtres

**Comment by Paulinelvq** [comment]
Je les ai tous vérifiés un à un

**Comment by Paulinelvq** [comment]
Désolée d'être un peu un boulet, mais je n'ai jamais fait de langage XML.........

**Comment by MyleneM** [comment]
@Paulinelvq Aucun problème :)
Tu as essayé de les tester avec Travis pour voir s'il détectait des erreurs ?
